### ISSUE TITLE
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "ingressroutes.traefik.containo.us" not found

### ISSUE THREAD

**Issue by DreamyKten** [tekumara/orion-demo#2]
Hello, 

I try to create a local cluster with the server but it's not working properly when the 

` kubectl get crd ingressroute.traefik.containo.us `

is executed after waiting more than 60 secs 

![image](https://user-images.githubusercontent.com/45590481/190448864-ceceafe6-858f-49db-a8a7-0c758dbf2c98.png)

thanks

**Comment by tekumara** [comment]
Is this using `make cluster`? What version of k3d do you have?

**Comment by DreamyKten** [comment]
k3d version v5.4.6
k3s version v1.24.4-k3s1 (default)

**Comment by tekumara** [comment]
Those versions should work ... How long did you wait for in total?

**Comment by DreamyKten** [comment]
I wait for at least 10 min. I still have this error : 
```
kubectl get crd ingressroute.traefik.containo.us > /dev/null
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "ingressroute.traefik.containo.us" not found
```

**Comment by tekumara** [comment]
I wonder if the kubeconfig is wrong. Could you tell me what the output of the following command is:
```
k3d kubeconfig write orion
```

**Comment by DreamyKten** [comment]
a link to the .k3d/kubeconfig-orion.yaml file with : 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFF ...
    server: https://0.0.0.0:38051
  name: k3d-orion
contexts:
- context:
    cluster: k3d-orion
    user: admin@k3d-orion
  name: k3d-orion
current-context: k3d-orion
kind: Config
preferences: {}
users:
- name: admin@k3d-orion
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJSDBGK ...
    client-key-data: LS0tLS1CRUdJTiBFQy ....
```
